/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.progcalc.app;

public final class R {
  public static final class dimen {
    public static final int umeng_fi_bottom_margin=0x7f010000;
    public static final int umeng_fi_drag_edge_bottom=0x7f010001;
    public static final int umeng_fi_drag_edge_lr=0x7f010002;
    public static final int umeng_fi_drag_edge_top=0x7f010003;
  }
  public static final class drawable {
    public static final int ic_launcher_background=0x7f020000;
    public static final int ic_launcher_foreground=0x7f020001;
    public static final int umeng_btn_blue=0x7f020002;
    public static final int umeng_dl_bg_shape=0x7f020003;
    public static final int umeng_dl_btn_bg=0x7f020004;
    public static final int umeng_ntf_pb=0x7f020005;
    public static final int umeng_pb=0x7f020006;
    public static final int umeng_reward_ad_info_btn_bg=0x7f020007;
    public static final int umeng_reward_ad_info_icon_bg=0x7f020008;
    public static final int umeng_reward_ad_info_layout_bg=0x7f020009;
    public static final int umeng_reward_ad_info_tips_layout_bg=0x7f02000a;
    public static final int umeng_reward_experience_tips_ad_info_layout_bg=0x7f02000b;
    public static final int umeng_reward_experience_tips_btn_bg=0x7f02000c;
    public static final int umeng_reward_experience_tips_btn_giveup_bg=0x7f02000d;
    public static final int umeng_splash_skip=0x7f02000e;
    public static final int umeng_union_close=0x7f02000f;
    public static final int umeng_union_close2=0x7f020010;
    public static final int umeng_union_dl_done=0x7f020011;
    public static final int umeng_union_dl_down_arrow=0x7f020012;
    public static final int umeng_union_dl_icon=0x7f020013;
    public static final int umeng_union_dl_pause=0x7f020014;
    public static final int umeng_union_dl_refresh=0x7f020015;
    public static final int umeng_union_dl_resume=0x7f020016;
    public static final int umeng_union_error=0x7f020017;
    public static final int umeng_union_fb_mark=0x7f020018;
    public static final int umeng_union_fi_close=0x7f020019;
    public static final int umeng_union_fi_mark=0x7f02001a;
    public static final int umeng_union_lp_back=0x7f02001b;
    public static final int umeng_union_lp_close=0x7f02001c;
    public static final int umeng_union_reward_gift=0x7f02001d;
    public static final int umeng_union_sound_off=0x7f02001e;
    public static final int umeng_union_sound_on=0x7f02001f;
    public static final int umeng_union_splash_action=0x7f020020;
    public static final int umeng_union_splash_mark=0x7f020021;
    public static final int umeng_union_splash_mark_new=0x7f020022;
    public static final int umeng_union_splash_shake=0x7f020023;
  }
  public static final class id {
    public static final int u_push_notification_banner_image=0x7f030000;
    public static final int u_push_notification_content=0x7f030001;
    public static final int u_push_notification_icon=0x7f030002;
    public static final int u_push_notification_title=0x7f030003;
    public static final int u_push_notification_top=0x7f030004;
    public static final int um_dl_app=0x7f030005;
    public static final int um_dl_app_perms_layout=0x7f030006;
    public static final int um_dl_btm=0x7f030007;
    public static final int um_dl_btn_action=0x7f030008;
    public static final int um_dl_btn_close=0x7f030009;
    public static final int um_dl_divider=0x7f03000a;
    public static final int um_dl_iv_app_icon=0x7f03000b;
    public static final int um_dl_tv_app_detail=0x7f03000c;
    public static final int um_dl_tv_app_name=0x7f03000d;
    public static final int um_dl_tv_app_owner=0x7f03000e;
    public static final int um_dl_tv_app_perms=0x7f03000f;
    public static final int um_dl_tv_app_privacy=0x7f030010;
    public static final int um_dl_tv_app_time=0x7f030011;
    public static final int um_dl_tv_app_version=0x7f030012;
    public static final int um_dl_web_divider=0x7f030013;
    public static final int um_dl_web_ib_back=0x7f030014;
    public static final int um_dl_web_layout=0x7f030015;
    public static final int um_dl_web_view=0x7f030016;
    public static final int um_download_notification_btn=0x7f030017;
    public static final int um_download_notification_btn_rl=0x7f030018;
    public static final int um_download_notification_iv=0x7f030019;
    public static final int um_download_notification_pg_tv=0x7f03001a;
    public static final int um_download_notification_pgbar=0x7f03001b;
    public static final int um_download_notification_rl=0x7f03001c;
    public static final int um_download_notification_title=0x7f03001d;
    public static final int um_ib_back=0x7f03001e;
    public static final int um_ib_close=0x7f03001f;
    public static final int um_interstitial_bottom=0x7f030020;
    public static final int um_interstitial_btn_detail=0x7f030021;
    public static final int um_interstitial_content=0x7f030022;
    public static final int um_interstitial_frame=0x7f030023;
    public static final int um_interstitial_iv_close=0x7f030024;
    public static final int um_interstitial_iv_logo=0x7f030025;
    public static final int um_interstitial_mark=0x7f030026;
    public static final int um_interstitial_shake=0x7f030027;
    public static final int um_interstitial_tv_content=0x7f030028;
    public static final int um_interstitial_tv_title=0x7f030029;
    public static final int um_landingpage_error_iv=0x7f03002a;
    public static final int um_landingpage_webview=0x7f03002b;
    public static final int um_pb=0x7f03002c;
    public static final int um_tv_title=0x7f03002d;
    public static final int umeng_reward_ad_info_btn=0x7f03002e;
    public static final int umeng_reward_ad_info_content_tv=0x7f03002f;
    public static final int umeng_reward_ad_info_detail_layout=0x7f030030;
    public static final int umeng_reward_ad_info_iv=0x7f030031;
    public static final int umeng_reward_ad_info_layout=0x7f030032;
    public static final int umeng_reward_ad_info_tips_layout=0x7f030033;
    public static final int umeng_reward_ad_info_tips_tv=0x7f030034;
    public static final int umeng_reward_ad_info_title_tv=0x7f030035;
    public static final int umeng_reward_close_tv=0x7f030036;
    public static final int umeng_reward_content=0x7f030037;
    public static final int umeng_reward_countdown_tv=0x7f030038;
    public static final int umeng_reward_mark=0x7f030039;
    public static final int umeng_reward_shake=0x7f03003a;
    public static final int umeng_reward_sounds_iv=0x7f03003b;
    public static final int umeng_reward_tips_ad_info_content_tv=0x7f03003c;
    public static final int umeng_reward_tips_ad_info_iv=0x7f03003d;
    public static final int umeng_reward_tips_ad_info_layout=0x7f03003e;
    public static final int umeng_reward_tips_ad_info_title_tv=0x7f03003f;
    public static final int umeng_reward_tips_cancel_btn=0x7f030040;
    public static final int umeng_reward_tips_content=0x7f030041;
    public static final int umeng_reward_tips_default_title_tv=0x7f030042;
    public static final int umeng_reward_tips_gift_iv=0x7f030043;
    public static final int umeng_reward_tips_ok_btn=0x7f030044;
    public static final int umeng_reward_tips_root=0x7f030045;
    public static final int umeng_reward_tips_scroll=0x7f030046;
    public static final int umeng_reward_tips_title_tv=0x7f030047;
    public static final int umeng_reward_title_layout=0x7f030048;
    public static final int umeng_reward_title_tv=0x7f030049;
    public static final int umeng_splash_action=0x7f03004a;
    public static final int umeng_splash_action_layout=0x7f03004b;
    public static final int umeng_splash_content=0x7f03004c;
    public static final int umeng_splash_countdown_tv=0x7f03004d;
    public static final int umeng_splash_mark=0x7f03004e;
    public static final int umeng_splash_shake=0x7f03004f;
  }
  public static final class layout {
    public static final int umeng_dl_layout=0x7f040000;
    public static final int umeng_dl_ntf_layout=0x7f040001;
    public static final int umeng_dl_simple_layout=0x7f040002;
    public static final int umeng_interstitial_layout=0x7f040003;
    public static final int umeng_ntf_layout=0x7f040004;
    public static final int umeng_reward_layout=0x7f040005;
    public static final int umeng_reward_tips_layout=0x7f040006;
    public static final int umeng_splash_layout=0x7f040007;
    public static final int umeng_web_layout=0x7f040008;
  }
  public static final class mipmap {
    public static final int ic_launcher=0x7f050000;
    public static final int ic_launcher_round=0x7f050001;
  }
  public static final class string {
    public static final int app_name=0x7f060000;
    public static final int umeng_ad_info_click_open=0x7f060001;
    public static final int umeng_ad_reward_btn_cancel=0x7f060002;
    public static final int umeng_ad_reward_btn_go=0x7f060003;
    public static final int umeng_ad_reward_btn_go_again=0x7f060004;
    public static final int umeng_ad_reward_btn_ok=0x7f060005;
    public static final int umeng_ad_reward_btn_play_again=0x7f060006;
    public static final int umeng_ad_reward_error_tips=0x7f060007;
    public static final int umeng_ad_reward_task_not_finish=0x7f060008;
    public static final int umeng_ad_reward_video_not_finish=0x7f060009;
    public static final int umeng_btn_detail=0x7f06000a;
    public static final int umeng_dl_app_desc=0x7f06000b;
    public static final int umeng_dl_app_dev=0x7f06000c;
    public static final int umeng_dl_app_permissions=0x7f06000d;
    public static final int umeng_dl_app_privacy=0x7f06000e;
    public static final int umeng_dl_app_time=0x7f06000f;
    public static final int umeng_dl_app_ver=0x7f060010;
    public static final int umeng_dl_cancel=0x7f060011;
    public static final int umeng_dl_dlt_msg=0x7f060012;
    public static final int umeng_dl_dlt_tips=0x7f060013;
    public static final int umeng_dl_done_tips=0x7f060014;
    public static final int umeng_dl_err_t=0x7f060015;
    public static final int umeng_dl_error_tips=0x7f060016;
    public static final int umeng_dl_ok=0x7f060017;
    public static final int umeng_dl_pause_t=0x7f060018;
    public static final int umeng_dl_paused_tips=0x7f060019;
    public static final int umeng_dl_start=0x7f06001a;
    public static final int umeng_dl_start_c=0x7f06001b;
    public static final int umeng_dl_start_t=0x7f06001c;
    public static final int umeng_dl_task_full=0x7f06001d;
    public static final int umeng_reward_close_cd=0x7f06001e;
    public static final int umeng_splash_skip_cd=0x7f06001f;
  }
  public static final class style {
    public static final int AppTheme=0x7f070000;
  }
  public static final class xml {
    public static final int umeng_file_paths=0x7f080000;
  }
}